spring:
  config:
    activate:
      on-profile: dev
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: root
    password: root

  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: skyworth123
    lettuce:
      shutdown-timeout: 100
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
mybatis-plus:
  mapper-locations: classpath:com/admin/firebase/*/mapper/mapping/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    type-aliases-package: com.admin.*.*.entity

server:
  port: 8088

jwt:
  key: skyworth.123

security:
  secret: skyworth

httpUrl: http://172.24.76.247:8888/


minio:
  endpoint: http://172.24.76.247:9000 #换成自己的minio服务端地址
  access-key: UxtxkQQIURHfQrrr
  secret-key: j38wpWJSqbTHlKP7W1kylZ1qTihkft5T
  bucket-name: firebase

#fdfs:
#  so-timeout: 5000 # 读取时间
#  connect-timeout: 60000 # 连接超时时间
#  thumb-image: # 生成缩略图
#    height: 150 # 缩略图高度
#    width: 150 # 缩略图宽度
#  tracker-list: # tracker 服务器地址
#    - 172.24.76.247:22122
#  web-server-url: http://172.24.76.247:8888/ # storage 服务器上nginx的地址
#  pool: # 可参考 ConnectionPoolConfig
#    #从池中借出的对象的最大数目（配置为-1表示不限制）
#    max-total: -1
#    #获取连接时的最大等待毫秒数(默认配置为5秒)
#    max-wait-millis: 5000
#    #每个key最大连接数  key配置的是连接服务端的地址(IP+端口)连接情况，如果有连接不够用的情况可以调整以上参数
#    max-total-per-key: 50
#    #每个key对应的连接池最大空闲连接数
#    max-idle-per-key: 10
#    #每个key对应的连接池最小空闲连接数
#    min-idle-per-key: 5
#    #向调用者输出“连接”资源时，是否检测有效性
#    test-on-borrow: true