spring:
  config:
    activate:
      on-profile: dev
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    hikari:
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 15
      # 自动提交
      auto-commit: true
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      idle-timeout: 600000
      pool-name: FireBaseHikariCP
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->
      max-lifetime: 28740000

  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: skyworth123
    lettuce:
      shutdown-timeout: 100
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
mybatis-plus:
  mapper-locations: classpath:com/admin/firebase/*/mapper/mapping/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    type-aliases-package: com.admin.*.*.entity

server:
  port: 8002

jwt:
  key: skyworth.123

security:
  secret: skyworth

httpUrl: http://172.24.76.247:8888/


minio:
  endpoint: http://172.24.76.247:9000 #换成自己的minio服务端地址
  access-key: UxtxkQQIURHfQrrr
  secret-key: j38wpWJSqbTHlKP7W1kylZ1qTihkft5T
  bucket-name: firebase

web:
  redirect-url: http://localhost:3000/login

justAuth:
  enabled: true
  cache:
    type: redis
  type:
    AMAZON:
      client-id: amzn1.application-oa2-client.5069407d05db4fd992adbb688f9f4316
      client-secret: amzn1.oa2-cs.v1.5d77d791de04233b88408ee69ce63d11ba5dcfe1e0387a7acb826502331837aa
      redirect-uri: http://localhost:8002/oauth/amazon/callback #项目中的回调地址
    GOOGLE:
      client-id: 273221647301-racglb8a3u2erd9jlsfilesdaj4f5gc4.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: https://localhost:8443/login #项目中的回调地址

